#!/usr/bin/env bash
# Installs, configures, and starts the server

# Update package lists
apt-get update

# Install Nginx
apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create directory for web content and set permissions
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create index.html with "Hello World!" message
echo 'Hello World!' > /var/www/html/index.html

# Define Nginx server configuration
SERVER_CONFIG="\
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"

# Write server configuration to Nginx default site configuration file
echo "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

# Check if Nginx is running and start or restart it
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi
