#!/usr/bin/env bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 18.234.168.254:80 check
    server web-02 34.207.155.252:80 check
EOT

# Restart HAProxy
service haproxy start

sudo systemctl restart haproxy